### ISSUE TITLE
Property 'speechBuilder' in type 'GoogleAction' is not assignable to the same property in base type 'Jovo'

### ISSUE THREAD

**Issue by florianthoma** [jovotech/jovo-sample-voice-app-typescript#3]
After running the `tsc` command I'm getting this error - is there a conflict with the different plugins? Thanks a lot for your help.
```
node_modules/jovo-platform-googleassistant/dist/src/core/GoogleAction.d.ts:11:5 - error TS2416: Property 'speechBuilder' in type 'GoogleAction' is not assignable to the same property in base type 'Jovo'.

Type '() => GoogleActionSpeechBuilder' is not assignable to type '() => SpeechBuilder | undefined'.
    Type 'GoogleActionSpeechBuilder' is not assignable to type 'SpeechBuilder'.
      Types of property 'addAudio' are incompatible.
        Type '(url: string, text: string | undefined, condition: boolean, probability: number) => GoogleActionSpeechBuilder' is not assignable to type '(url: string | string[], condition?: boolean | undefined, probability?: number | undefined) => SpeechBuilder'.
speechBuilder(): GoogleActionSpeechBuilder;
```

**Comment by jankoenig** [comment]
Hi @florianthoma. Thanks for bringing this up, we're taking a look

**Comment by probststefan** [comment]
@jankoenig I can't get this project going either. Do you already know why that is?

**Comment by aswetlow** [comment]
Hey!
We will publish an update later today.

**Comment by aswetlow** [comment]
Done. Please update your project.

**Comment by probststefan** [comment]
@aswetlow Thank you! It's working now! :)

But now i ran into another problem:

`this.ask(this.t('WELCOME_RETURNING_USER_SPEECH'),this.t('WELCOME_RETURNING_USER_REPROMPT'));`

Error:(46, 22) TS2345:Argument of type 'string | string[]' is not assignable to parameter of type 'string | SpeechBuilder'.
  Type 'string[]' is not assignable to type 'string | SpeechBuilder'.
    Type 'string[]' is not assignable to type 'SpeechBuilder'.
      Property 'speech' is missing in type 'string[]'.

**Comment by m-ripper** [comment]
Hello @probststefan,
this issue should be fixed if you change this line to:
`this.ask(this.t('WELCOME_RETURNING_USER_SPEECH').toString(),this.t('WELCOME_RETURNING_USER_REPROMPT').toString());`
Basically `this.t(id)` does not return a string but a i18n-specific type `TranslateResult` which can be easily turned into a string.
Hopefully this does resolve the issue for you.

**Comment by probststefan** [comment]
I've tried that. Only the key is returned, not the translated value.

**Comment by m-ripper** [comment]
Is the translation-entry for `WELCOME_RETURNING_USER_SPEECH` an array or a single string?

**Comment by probststefan** [comment]
single string

**Comment by m-ripper** [comment]
This is weird. We'll look into that.

**Comment by probststefan** [comment]
Sorry for all the problems. I believe the problem is in my config.ts. How would you load your translation file?

```
    i18n: {
        returnNull: false,
        fallbackLng: 'de-DE',
        resources: {
            'de-DE': require('i18n/de-DE.json'),
        }
    },
```

**Comment by probststefan** [comment]
Got it working!

Added this to compilerOptions:
"resolveJsonModule": true

and imported the json like this:
import json = require('./i18n/de-DE.json');

**Comment by m-ripper** [comment]
Alright, I was going to point out that the i18n-folder contents are not being moved upon compiling via `npm run tsc`, but I am glad you got it fixed now.

For other people possibly reading this in the future:
You can either do it the same way as @probststefan or manually copy the `i18n` folder with it's content into dist after running `npm run tsc`.

**Comment by Laazarus** [comment]
Hello, I am having a really hard time using Jovo v2 and typescript when integrating the google spreadsheet as CMS.

I have followed the instructions and also this thread but when I am trying to access my data hosted in the sheet I am getting only the key value back. I am not sure if I have to set the i18n in the config file (I am sure it does something but I have followed the video tutorial and the docs and in order to use the CMS does not seems like I have to set the i18n).

Any help would be really appreciated :)

**Comment by Jefftopia** [comment]
~I'm still getting a host of compilation errors.~

Running `npm update` and **installing types for node, socket.io, and express**  fixed most of these. 

1. _Fixed_: See my comment below this one.
```
node_modules/jovo-core/dist/src/Extensible.d.ts:12:50 - error TS2507: Type 'typeof internal' is not a constructor function type.

12 export declare abstract class Extensible extends EventEmitter implements Plugin {
                                                    ~~~~~~~~~~~~
```

2. _Fixed_: `npm install --save-dev @types/express`.
```
node_modules/jovo-framework/dist/src/index.d.ts:16:16 - error TS2665: Invalid module name in augmentation. Module 'express' resolves to an untyped module at '/Users/jsmith582/dev/chuck/node_modules/express/index.js', which cannot be augm
ented.

16 declare module 'express' {
                  ~~~~~~~~~
```

3. _Fixed_: `npm install --save-dev @types/express`.
```
node_modules/jovo-framework/dist/src/server.d.ts:1:26 - error TS7016: Could not find a declaration file for module 'express'. '/Users/jsmith582/dev/chuck/node_modules/express/index.js' implicitly has an 'any' type.
  Try `npm install @types/express` if it exists or add a new declaration (.d.ts) file containing `declare module 'express';`

1 import * as express from 'express';
                           ~~~~~~~~~
```

4. _Fixed_: See my comment _below this one_.
```
node_modules/jovo-framework/node_modules/jovo-core/dist/src/Extensible.d.ts:12:50 - error TS2507: Type 'typeof internal' is not a constructor function type.

12 export declare abstract class Extensible extends EventEmitter implements Plugin {
                                                    ~~~~~~~~~~~~
```

5. _Fixed_: `npm install --save-dev @types/socket.io-client`.
```
node_modules/jovo-plugin-debugger/dist/src/JovoDebugger.d.ts:1:23 - error TS2688: Cannot find type definition file for 'socket.io-client'.

1 /// <reference types="socket.io-client" />
                        ~~~~~~~~~~~~~~~~
```

6. `npm install --save-dev @types/socket.io-client`.
```
node_modules/jovo-plugin-debugger/dist/src/JovoDebugger.d.ts:36:14 - error TS2503: Cannot find namespace 'SocketIOClient'.

36     socket?: SocketIOClient.Socket;
```

Here's my package.json

```
{
    "compilerOptions": {
        "lib": [
            "es2017"
        ],
        "allowUnreachableCode": false,
        "noImplicitReturns": true,
        "preserveConstEnums": true,
        "experimentalDecorators": true,
        "noImplicitAny": true,
        "removeComments": true,
        "module": "commonjs",
        "outDir": "lib",
        "sourceMap": true,
        "target": "es2017",
        "rootDir": ".",
        "resolveJsonModule": true,
        "esModuleInterop": true,
        "strict": true
    },
    "compileOnSave": true,
    "include": [
        "**/*.d.ts",
        "src",
        "rms"
    ],
    "exclude": [
        "scripts",
        "bin",
        "dist",
        "lib",
        "depr",
        "node_modules/**/*"
    ]
}
```

I'm using Typescript version 3.3.4000

**Comment by Jefftopia** [comment]
I think there's a problem with the EventEmitter use in `jovo-core/dist/src/Extensible.d.ts`.

```
/// <reference types="node" />
import * as EventEmitter from "events";

export declare abstract class Extensible extends EventEmitter implements Plugin {
```

It looks like you're trying to extend a _class_ even though the imported _thing_ is a _module_.

When I change the .d.ts file in the following way, two of my errors are resolved.

```
import { EventEmitter } from "events";
export declare abstract class Extensible extends EventEmitter implements Plugin {
```

OR

```
import * as Events from "events";
export declare abstract class Extensible extends Events.EventEmitter implements Plugin {
```

PS: Do you need `/// <reference types="node" />`? I don't believe so. This is what `@types` are for. And TypeScript comes with node typings out of the box. Add

// tsconfig.json
```
"compilerOptions" {
    "types": ["node"],
}
```
